/* ==========================================================================
   United States Universities For Ukraine — search-data.js

   Static index for the site search (see the search module in main.js).
   One entry per destination a visitor might look for:
     path    — breadcrumb-style label shown above the result title
     title   — result headline
     url     — where the result leads
     text    — short line shown under the title
     keywords— extra words to match that don't appear in title/text

   When pages gain real copy, extend `text` and `keywords` so results
   keep matching what people actually type.
   ========================================================================== */

window.USUFU_SEARCH_INDEX = [
  // --- Top-level pages ---
  { path: "Home", title: "United States Universities For Ukraine", url: "index.html",
    text: "Your path to a U.S. education starts right here.",
    keywords: "usufu home main start welcome",
    uk: "юсуфу головна сайт початок україна" },
  { path: "Programs", title: "Discover Your Level", url: "programs.html",
    text: "Get to know your level and what matters in it.",
    keywords: "grade level education study",
    uk: "програми рівні класи школа навчання"},
  { path: "Programs", title: "Our Help", url: "help.html",
    text: "Explore everything we help with.",
    keywords: "support areas services assistance",
    uk: "допомога підтримка напрями"},
  { path: "About", title: "About Us", url: "about.html",
    text: "An organization built on open doors.",
    keywords: "who we are organization nonprofit",
    uk: "про нас організація місія"},
  { path: "Contact", title: "Contact Us", url: "contact.html",
    text: "Send us a message — we answer every single time.",
    keywords: "email message reach write form question",
    uk: "контакти написати звернутися пошта форма"},
  { path: "News", title: "News", url: "news.html",
    text: "Stories, guides, updates and events.",
    keywords: "blog articles stories press",
    uk: "новини статті історії блог"},
  { path: "Resources", title: "Resources", url: "resources.html",
    text: "Guides and answers in one place.",
    keywords: "library materials downloads",
    uk: "ресурси бібліотека посібники"},
  { path: "Resources", title: "FAQ — Frequently Asked Questions", url: "faq.html",
    text: "Questions, answered.",
    keywords: "faq help answers cost eligibility apply",
    uk: "питання відповіді"},
  { path: "Get Involved", title: "Get Involved", url: "get-involved.html",
    text: "Three ways to open a door: donate, volunteer, partner.",
    keywords: "support contribute join",
    uk: "долучитися допомогти внесок"},

  // --- Grade levels ---
  { path: "Programs", title: "Middle School (Grades 6–8)", url: "middle-school.html",
    text: "Start early, dream bigger — math placement, electives and the habits that compound.",
    keywords: "grade 6 7 8 middle school young students algebra math placement tracking electives language",
    uk: "середня школа класи математика розподіл мова"},
  { path: "Programs", title: "High School (Grades 9–12)", url: "high-school.html",
    text: "Four years that open every door — credits, GPA, rigour, tests and senior year.",
    keywords: "grade 9 10 11 12 high school teenagers credits gpa weighted unweighted rigour ap ib honors psat senior rank",
    uk: "старша школа класи credits gpa складність тести"},
  { path: "Programs", title: "University & Beyond", url: "university.html",
    text: "From application to graduation — how a degree is built, paid for, and what comes after.",
    keywords: "college undergraduate graduate applicants students major credits net price aid opt stem h-1b community college",
    uk: "університет коледж студенти абітурієнти диплом major вартість робота"},

  // --- Support areas ---
  { path: "Our Help", title: "Admissions Support", url: "admissions.html",
    text: "Admissions, step by step.",
    keywords: "apply application essays deadlines requirements",
    uk: "вступ заявка подання документи"},
  { path: "Our Help", title: "Scholarships", url: "scholarships.html",
    text: "Funding within your reach.",
    keywords: "money funding financial aid tuition grants",
    uk: "стипендія стипендії гроші фінансування грант"},
  { path: "Our Help", title: "We Answer Questions", url: "mentorship.html",
    text: "No mentors needed - just ask us anything, any time.",
    keywords: "questions ask answer support reach out help",
    uk: "питання запитати відповідь підтримка звернутися" },
  { path: "Our Help", title: "Visas & Documents", url: "visas.html",
    text: "Paperwork, without the panic.",
    keywords: "visa f-1 i-20 passport documents immigration",
    uk: "віза візи документи паспорт співбесіда"},
  { path: "Our Help", title: "Campus Life", url: "campus-life.html",
    text: "Your first semester on campus, one item at a time.",
    keywords: "housing dorm student life community campus insurance ssn bank orientation dso classes gpa",
    uk: "кампус гуртожиток життя студентське перший семестр страхування"},
  { path: "Guides", title: "A Parent's Handbook", url: "parents.html",
    text: "The whole journey, explained for parents and families.",
    keywords: "parent parents family guardian ferpa cost money help journey guide 05",
    uk: "батьки родина довідник батьківський гроші допомога ferpa"},

  // --- Ways to help ---
  { path: "Get Involved", title: "Donate", url: "donate.html",
    text: "Every gift opens a door.",
    keywords: "donation give money support gift charity",
    uk: "пожертва донат підтримати внесок"},
  { path: "Get Involved", title: "Volunteer", url: "volunteer.html",
    text: "Give an hour, change a path.",
    keywords: "volunteer mentor translate review essays help others",
    uk: "волонтер волонтерство допомагати"},
  { path: "Get Involved", title: "Partner", url: "partner.html",
    text: "Stronger together.",
    keywords: "partnership university company institution collaborate",
    uk: "партнер партнерство співпраця університети"},

  // --- Useful hub ---
  { path: "Resources", title: "Useful", url: "useful.html",
    text: "Materials, videos, timelines and dates — the practical hub.",
    keywords: "hub tools practical downloads",
    uk: "корисне інструменти хаб"},
  { path: "Useful", title: "Materials", url: "materials.html",
    text: "Downloadable practice tests, guides and templates.",
    keywords: "download pdf sat practice test bundle templates guides files",
    uk: "матеріали завантажити тест тренувальний шаблони"},
  { path: "Useful", title: "Video Library", url: "videos.html",
    text: "Walkthroughs and explainers, chapter by chapter.",
    keywords: "video watch youtube chapters timestamps explainer",
    uk: "відео відеотека дивитися розділи"},
  { path: "Useful", title: "Timelines", url: "timelines.html",
    text: "Countdown to the school year and the moments when things must start.",
    keywords: "countdown timer deadline school year summer when start",
    uk: "таймлайн таймлайни відлік дедлайн коли починати"},
  { path: "Useful", title: "Dates", url: "dates.html",
    text: "Official SAT, ACT, TOEFL, FAFSA and application dates.",
    keywords: "sat act toefl fafsa common app test dates calendar deadlines",
    uk: "дати календар іспити дедлайни"},
  { path: "Timelines", title: "Leveled Timelines", url: "leveled-timelines.html",
    text: "Season-by-season timelines for every education level.",
    keywords: "timeline level season year plan when what to do",
    uk: "таймлайн рівень сезон рік план коли що робити" },
  { path: "Timelines", title: "Middle School Timeline", url: "timeline-middle-school.html",
    text: "Grades 6\u20138, season by season.",
    keywords: "middle school timeline grade 6 7 8 seasons",
    uk: "середня школа таймлайн класи сезони" },
  { path: "Timelines", title: "High School Timeline", url: "timeline-high-school.html",
    text: "Grades 9\u201312 \u2014 every season has a deadline.",
    keywords: "high school timeline grade 9 10 11 12 seasons freshman senior",
    uk: "старша школа таймлайн класи сезони випускний" },
  { path: "Timelines", title: "University Timeline", url: "timeline-university.html",
    text: "From the application year to graduation.",
    keywords: "university college timeline application graduation stages",
    uk: "університет таймлайн заявка випуск етапи" },
  { path: "Useful", title: "Calculator", url: "calculators.html",
    text: "The GPA calculator that matches your school's exact rules.",
    keywords: "gpa calculator final exam grade weighted 4.0 5.0 score need",
    uk: "калькулятор середній бал оцінки іспит порахувати"},
  { path: "Useful", title: "College List Builder", url: "college-list.html",
    text: "Your estimated GPA and test scores turned into a balanced list — reach, target and safety, with affordability shown next to each school.",
    keywords: "college list builder match reach target safety school list chances admission fit balanced apply where",
    uk: "список університетів куди подаватися шанси реач таргет сейфті добірка вступ"},
  { path: "Useful", title: "Funding Gap Calculator", url: "funding-gap.html",
    text: "What a first year at each school on your list really costs you, and whether you can document enough to be issued the I-20 your F-1 visa depends on.",
    keywords: "funding gap i20 i-20 f1 f-1 visa net price cost of attendance proof of funds certification finances sponsor bank statement education loan afford pay tuition first year",
    uk: "дефіцит фінансування i20 віза f1 підтвердження коштів вартість навчання спонсор виписка кредит чиста вартість перший рік"},
  { path: "Useful", title: "Visa & Document Scheduler", url: "visa-scheduler.html",
    text: "Work backward from your application deadline or program start date to the latest safe date to begin each step — apostille, translation, SEVIS, and the third-country interview.",
    keywords: "visa scheduler f1 f-1 sevis i-901 apostille translation interview appointment wait time third country warsaw prague embassy kyiv i-20 deadline timeline backward schedule documents passport",
    uk: "віза графік апостиль переклад співбесіда посольство сертифікат sevis дедлайн терміни документи третя країна варшава прага розклад"},
  { path: "About", title: "USUFU SAT Prep — the app", url: "satprep.html",
    text: "Coming soon — our free desktop app: turn a College Board Question Bank PDF into a practice test that behaves like Bluebook.",
    keywords: "sat prep app coming soon release preview desktop mac macos windows linux bluebook question bank practice test psat nmsqt timed flashcards vocabulary offline free college board digital sat module adaptive statistics spaced repetition",
    uk: "sat підготовка застосунок програма завантажити мак віндовс лінукс блубук банк питань тренувальний тест psat картки словник офлайн безкоштовно"},
  { path: "Useful", title: "Financial Aid Finder", url: "financial-aid-finder.html",
    text: "US universities filtered by international aid policy: need-blind, need-aware, meets full need — with sources.",
    keywords: "financial aid international need blind need aware full need scholarships universities colleges money funding list finder",
    uk: "фінансова допомога іноземці університети need blind стипендія пошук фінансування"},
  { path: "Useful", title: "Education Record Helper", url: "timeline-builder.html",
    text: "Interrupted schooling, explained once — build your timeline, flag the gaps, and prepare short factual context.",
    keywords: "gap year interrupted education record transcript missing explain additional information common app displaced relocation timeline builder",
    uk: "прогалина перерване навчання пояснити атестат переїзд війна таймлайн історія"},
  { path: "Calculators", title: "Ukrainian Grade Converter", url: "calculators.html#ua-gpa",
    text: "Ukrainian 12-point, 5-point, 100-point and ECTS grades to an estimated US 4.0 GPA.",
    keywords: "ukraine grades convert 12 point 100 point ects transcript wes atestat gpa equivalent",
    uk: "конвертер оцінки атестат 12 бальна 100 бальна переведення американський"},
  { path: "Calculators", title: "NMT → SAT/ACT Estimator", url: "calculators.html#nmt",
    text: "Where your NMT score roughly lands on the SAT and ACT — a percentile-anchored range.",
    keywords: "nmt zno sat act convert estimate score range percentile test",
    uk: "нмт зно бали переведення оцінка тест вилка"},
  { path: "Useful", title: "Finances", url: "finances.html",
    text: "What a year of college truly costs, and what your AP & IB scores are worth.",
    keywords: "money cost tuition price financial aid award letter net out of pocket budget",
    uk: "фінанси гроші вартість навчання ціна бюджет фінансова допомога"},
  { path: "Finances", title: "True Cost of Attendance", url: "finances.html#true-cost",
    text: "Turn a financial aid letter into the real price of a year.",
    keywords: "coa sticker price gift aid grants scholarships housing meal plan books hidden costs",
    uk: "справжня вартість рік гранти стипендії житло харчування книжки"},
  { path: "Finances", title: "AP & IB Credit Value", url: "finances.html#credit-value",
    text: "How far your exam scores carry toward a degree — and what they save in tuition.",
    keywords: "ap ib exam score college credits transfer savings 120 tier placement",
    uk: "кредити іспит бали переведення економія ступінь"},
  { path: "Timelines", title: "Countdown to College", url: "timelines.html#college-countdown",
    text: "A season-by-season admissions checklist built from your answers — downloadable as a PDF.",
    keywords: "checklist tasks deadlines early decision fafsa senior junior plan progress pdf download",
    uk: "чекліст завдання дедлайни план вступ прогрес" },
  { path: "Finances", title: "The Aid Letter De-Coder", url: "finances.html#decoder",
    text: "Compare up to three financial aid offers — free, earned and borrowed money, side by side.",
    keywords: "compare offers award letter net price loans debt work study grants decoder",
    uk: "порівняти пропозиції лист допомога позики борг гранти" },
  { path: "Useful", title: "College Life", url: "college-life.html",
    text: "The hidden curriculum: college jargon in plain English and the unwritten rules.",
    keywords: "jargon dictionary hidden curriculum terms slang syllabus bursar office hours fafsa registrar probation translate",
    uk: "жаргон словник терміни приховані правила переклад студентське життя"},
  { path: "College Life", title: "The Jargon Translator", url: "college-life.html#jargon",
    text: "Every confusing college term — official version, plain English, the unwritten rule, and your move.",
    keywords: "definitions glossary decoder terms meaning what does mean",
    uk: "словник значення термін що означає глосарій"},
  { path: "Finances", title: "The Major Pivot Risk Assessor", url: "finances.html#pivot",
    text: "Plan A vs. Plan B majors: the overlap score, safe-bet courses, and the cost of switching.",
    keywords: "change major switch pivot overlap credits plan b backup risk freshman courses",
    uk: "змінити спеціальність план б ризик кредити перший курс"},
  { path: "Useful", title: "Career Pathfinder", url: "pathfinder.html",
    text: "Three questions between you and a direction.",
    keywords: "quiz major career path stem business arts flowchart choose",
    uk: "професія спеціальність кар'єра тест квіз напрям"},

  // --- About sections ---
  { path: "About", title: "Our Mission", url: "about.html#mission",
    text: "Why we exist.",
    keywords: "mission purpose goal vision",
    uk: "місія навіщо цінності мета" },

  // --- Everything else ---
  { path: "Resources", title: "Guides", url: "resources.html#guides",
    text: "Step-by-step guides for every stage.",
    keywords: "guide how to steps handbook",
    uk: "довідники гайди інструкції покроково" },
  { path: "Legal", title: "Privacy Policy", url: "legal.html#privacy",
    text: "How your data is handled.",
    keywords: "privacy data protection gdpr",
    uk: "конфіденційність приватність дані персональні" },
  { path: "Legal", title: "Terms of Service", url: "legal.html#terms",
    text: "The rules of using this site.",
    keywords: "terms conditions legal",
    uk: "умови користування правила угода" },
  { path: "Legal", title: "Accessibility Statement", url: "legal.html#accessibility",
    text: "Our accessibility commitment.",
    keywords: "accessibility a11y wcag",
    uk: "доступність заява інклюзивність" },
];
